//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monopoly.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare bankruptcy.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bought {1}.
        /// </summary>
        public static string bought {
            get {
                return ResourceManager.GetString("bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string buystreet {
            get {
                return ResourceManager.GetString("buystreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get a chance card if you land here.
        /// </summary>
        public static string chance {
            get {
                return ResourceManager.GetString("chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has thrown{1}.
        /// </summary>
        public static string cheatdice {
            get {
                return ResourceManager.GetString("cheatdice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move player.
        /// </summary>
        public static string cheatmove {
            get {
                return ResourceManager.GetString("cheatmove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change player.
        /// </summary>
        public static string cheatplayer {
            get {
                return ResourceManager.GetString("cheatplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get a community card if you land here.
        /// </summary>
        public static string community {
            get {
                return ResourceManager.GetString("community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}this property is currently owned by {2}{1}it costs ${3} to buy this {1}If one &apos;Utility&apos; is owned rent is 4 times the amount shown on dice {1}If both &apos;utilities are owned rent is 10 times amount shown on dice. {1} Mortgage value is ${4}.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paid ${1} to {2}.
        /// </summary>
        public static string companypay {
            get {
                return ResourceManager.GetString("companypay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw your dice.
        /// </summary>
        public static string dice {
            get {
                return ResourceManager.GetString("dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} downgraded{1}.
        /// </summary>
        public static string downgrade {
            get {
                return ResourceManager.GetString("downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End your turn.
        /// </summary>
        public static string endturn {
            get {
                return ResourceManager.GetString("endturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you land here you get some hidden goodies, you lucky bastard.
        /// </summary>
        public static string freeparking {
            get {
                return ResourceManager.GetString("freeparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} found a hidden bag with ${1} in it.
        /// </summary>
        public static string freeparkingpay {
            get {
                return ResourceManager.GetString("freeparkingpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over.
        /// </summary>
        public static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to got.
        /// </summary>
        public static string got {
            get {
                return ResourceManager.GetString("got", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You go to jail for stealing soap.
        /// </summary>
        public static string gotojail {
            get {
                return ResourceManager.GetString("gotojail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t drop your soap.
        /// </summary>
        public static string jail {
            get {
                return ResourceManager.GetString("jail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is still in jail.
        /// </summary>
        public static string jailpeson {
            get {
                return ResourceManager.GetString("jailpeson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You visit jail to give your buddy soap because he somehow lost it.
        /// </summary>
        public static string jailvisit {
            get {
                return ResourceManager.GetString("jailvisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a game.
        /// </summary>
        public static string loadgame {
            get {
                return ResourceManager.GetString("loadgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage streets.
        /// </summary>
        public static string managestreets {
            get {
                return ResourceManager.GetString("managestreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortage.
        /// </summary>
        public static string mortage {
            get {
                return ResourceManager.GetString("mortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mortaged{1}.
        /// </summary>
        public static string mortaged {
            get {
                return ResourceManager.GetString("mortaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} moved to {1}.
        /// </summary>
        public static string moves {
            get {
                return ResourceManager.GetString("moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game.
        /// </summary>
        public static string newgame {
            get {
                return ResourceManager.GetString("newgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On mortage.
        /// </summary>
        public static string onmortage {
            get {
                return ResourceManager.GetString("onmortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free parking treasure:.
        /// </summary>
        public static string parkingmoney {
            get {
                return ResourceManager.GetString("parkingmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paid ${1} to {2}.
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {12} this property is currently owned by {1} {12} {2} it costs ${3} to buy this {12} Rent ${4} {12} Costs to upgrade your street: ${5} {12} With 1 house your rent is: ${6} {12} With 2 house your rent is: ${7} {12} With 3 house your rent is: ${8} {12} With 4 house your rent is: ${9} {12} With a hotel your rent is: ${10} {12} Mortgage value: ${11} {12} if you have the whole city the rent is doubled..
        /// </summary>
        public static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There have been {0} houses built in this street {1}.
        /// </summary>
        public static string propertyhouses {
            get {
                return ResourceManager.GetString("propertyhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nobody.
        /// </summary>
        public static string propertyowner {
            get {
                return ResourceManager.GetString("propertyowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} this railroad is currently owned by {2} {1} it costs ${3} to buy this {1} Rent when you have 1 railroad: ${4}{1} Rent when you have 2 railroads: ${5}{1} Rent when you have 3 railroads: ${6}{1} Rent when you have 4 railroads: ${7}{1} Mortage value: ${8}.
        /// </summary>
        public static string railroad {
            get {
                return ResourceManager.GetString("railroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade.
        /// </summary>
        public static string sellstreet {
            get {
                return ResourceManager.GetString("sellstreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}If you land on this tile you $400 {1}Else if you pass this tile you get $200.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} landed on start, he gets an extra $400.
        /// </summary>
        public static string startmoney {
            get {
                return ResourceManager.GetString("startmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately you have to pay taxes but don&apos;t worry {0} In real life you won&apos;t have to pay 10% of your total net worth!.
        /// </summary>
        public static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had to pay ${1}.
        /// </summary>
        public static string taxespay10 {
            get {
                return ResourceManager.GetString("taxespay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had to pay $200.
        /// </summary>
        public static string taxespay200 {
            get {
                return ResourceManager.GetString("taxespay200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has thrown {1} and {2}.
        /// </summary>
        public static string throwdice {
            get {
                return ResourceManager.GetString("throwdice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;b&apos; to  quickly buy a property.
        /// </summary>
        public static string tooltipbuy {
            get {
                return ResourceManager.GetString("tooltipbuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;t&apos; to quickly throw a dice..
        /// </summary>
        public static string tooltipdice {
            get {
                return ResourceManager.GetString("tooltipdice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;m&apos; to quickly manage your properties.
        /// </summary>
        public static string tooltipmanage {
            get {
                return ResourceManager.GetString("tooltipmanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;e&apos; to quickly end your turn..
        /// </summary>
        public static string tooltipturn {
            get {
                return ResourceManager.GetString("tooltipturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of players:.
        /// </summary>
        public static string totalplayers {
            get {
                return ResourceManager.GetString("totalplayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} upgraded {1}.
        /// </summary>
        public static string upgrade {
            get {
                return ResourceManager.GetString("upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgradecosts.
        /// </summary>
        public static string upgradecost {
            get {
                return ResourceManager.GetString("upgradecost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins!.
        /// </summary>
        public static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
    }
}
